name: Build and run ROS tests

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [foxy]

    runs-on: ubuntu-latest

    continue-on-error: true

    container:
      image: ros:${{ matrix.rosdistro }}-perception

    steps:
    - uses: actions/checkout@v2

    - name: Build and run tests
      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && ./ci.sh

