name: Build and run ROS tests

on:
  push:
    branches: [ kinetic-devel ]
  pull_request:
    branches: [ kinetic-devel ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ros:noetic-robot

    steps:
    - uses: actions/checkout@v2

    - name: Build and run tests
      run: . /opt/ros/noetic/setup.sh && ./ci.sh

